receivers:
  jaeger:
    protocols:
      thrift_compact:
      thrift_http:

  otlp:
    protocols:
      grpc:
      http:

exporters:
  influxdb:
    endpoint: https://eu-central-1-1.aws.cloud2.influxdata.com/
    bucket: otel
    token: YF54Dab9knxNZMkWbldlCAcr69lzWq7dUWmjk-DP_lcv9YgaXqZCy9t0IkJiwERFnADhFqyHjYiU6tKCk22gUg==
    metrics_schema: otel-v1

connectors:
  spanmetrics:
    aggregation_temporality: "AGGREGATION_TEMPORALITY_DELTA"
  servicegraph:

service:
  telemetry:
    logs:
      level: debug
      encoding: json

  pipelines:
    traces:
      receivers: [otlp, jaeger]
      exporters: [influxdb, spanmetrics, servicegraph]

    metrics:
      receivers: [spanmetrics, servicegraph]
      exporters: [influxdb]
